[toolchain]

[features]
resolution = true
skip-lint = true

[programs.devnet]
prediction_market = "Cqmj4eALsUv5DJMVKJ2o1FPYBjvp7oCyMrWbvVA38eaK"

[programs.mainnet]
prediction_market = "Cqmj4eALsUv5DJMVKJ2o1FPYBjvp7oCyMrWbvVA38eaK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
