[toolchain]

[features]
resolution = true
skip-lint = true

[programs.devnet]
basic_oracle_example = "11111111111111111111111111111111"

[programs.mainnet]
basic_oracle_example = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
