[toolchain]

[features]
resolution = true
skip-lint = true

[programs.devnet]
advanced_oracle_example = "DKpZoRdw6CkbQPCLuyeQsgLCh3kSaYKhGZ6fvgJCTMgr"

[programs.mainnet]
advanced_oracle_example = "AtzoHFHwuJs3BiP8zMnaoEo7q3Q7N6ACCUYL7jXhZ5en"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
