[toolchain]

[features]
resolution = true
skip-lint = true

[programs.devnet]
sb_randomness = "44wNsyMPUQxCDhJpKqwNu8XGjqYbThqgRPUpQCARyrUc"

[programs.mainnet]
sb_randomness = "DVM7r1LWrVYivfL2AYNWP7Kovj8bx8kh3VxeEw3zFVHB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
