[toolchain]

[features]
resolution = true
skip-lint = true

[programs.devnet]
pancake_stacker = "PANCAKE_STACKER_PROGRAM_ID"

[programs.mainnet]
pancake_stacker = "PANCAKE_STACKER_PROGRAM_ID"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
